pipeline: 
  render:
    image: ncatelli/hakyll:4.12.2
    pull: true
    commands:
      - cabal install 
      - cabal exec site rebuild

  s3-sync:
    image: plugins/s3-sync:1
    bucket: cohomolo-gy
    region: us-east-1
    source: _site/
    delete: true
    acl:
      '/**/*': public-read
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    when:
      event: push
      branch: master

  webhook:
    image: ncatelli/hugo_builder:v0.29
    commands:
      - 'curl -kH "Content-type: application/json" -H "Accept: application/json" -d "{\"urls\": [{\"url\": \"http://www.cohomolo.gy/*\"}]}" "$WEBHOOK_URLS" -u "$WEBHOOK_USERNAME:$WEBHOOK_PASSWORD" -s'
    secrets: [ webhook_username, webhook_password, webhook_urls ]
    when:
      event: push
      branch: master
